SELECT 
LeadID, 
[Auto Trial],
FirstName,
LastName,
Date_Time,
[Job Title],
Email, 
A.Country,
State,
[Creation Date to today _Days_],
[Lead Status],
[Lead Stage],
[Product Code],
[Marketing Interest],
UserID,
[Full Name],
[First Name],
[Last Name],
Email_Seller, 
[Unread By Owner],
cid,
Title,
Phone,
[Last Modified Date],
[Last Modified By: Full Name],
datename(weekday, Date_Time) as Date
FROM [AT_Lead_SellerProfiles] A INNER JOIN [All_Region_Countries] B
ON A.Country = B.COUNTRY
WHERE B.Territory = 'EMEA' AND B.Region = 'EME' AND A.Country <> 'United Kingdom' AND A.Country <> 'Ireland'