SELECT
     NEWID() as SubmissionId,
     (GETDATE() AT TIME ZONE 'Central Standard Time') AT TIME ZONE 'AUS Eastern Standard Time' as SubmittedDate,
     'False' as IsProcessed,
     FirstName, 
     LastName, 
     Email, 
     Phone, 
     Country, 
     State, 
     State__c, 
     PostalCode, 
     Title, 
     Job_Function__c, 
     Enquiry_Type__c, 
     Company, 
     Grade_Level__c, 
     No_of_licences__c, 
     Territory__c, 
     Campaign_Name__c, 
     Campaign_Code__c, 
     LeadSource, 
     Status, 
     Description, 
     Marketing_Interest__c, 
     Product_Interest__c, 
     Marketing_Product_Interest__c, 
     FileName
FROM [001_Lead_Data_Import_to_CRM_STAGING]