SELECT 
    cws.ContactKey,
    cws.SubscriptionProduct,
    cws.SubscriptionRecordType,
    cws.SubscriptionEndDate,
    cws.SubscriptionId,
    cws.ContactTitle,
    cws.ContactFirstName,
    cws.ContactLastName,
    cws.ContactEmail,
    cws.ContactMobilePhone,
    cws.ContactLocale,
    cws.HasOptedOutOfEmail,
    cws.ContactCreateDate,
    cws.ContactLastModifiedDate,
    cws.ContactJobFunction,
    cws.ContactStatus,
    cws.ContactRoles,
    cws.ContactTerritory,
    cws.ContactSalutation,
    cws.ContactProductInfluencer,
    cws.ContactMarketingInterest,
    cws.ContactMarketingProductInterest,
    cws.ContactRecordTypeID,
    cws.AccountId,
    cws.AccountName,
    cws.AccountGlobalSchoolCategory,
    cws.AccountLocalAuthority,
    cws.AccountOwnerId,
    cws.AccountBillingStreet,
    cws.AccountBillingCity,
    cws.AccountBillingState,
    cws.AccountBillingStateCode,
    cws.AccountBillingPostalCode,
    cws.AccountBillingCountry,
    cws.AccountBillingCountryCode,
    cws.AccountStatus,
    cws.ContractId,
    cws.ContractStartDate,
    cws.ContractEndDate,
    cws.ContractMultiYearExpiration,
    cws.OpportunityId,
    cws.QuoteId,
    cws.RenewalOpportunityId,
    cws.OpportunityType,
    cws.OpportunityStage,
    cws.OpportunityOwnerId,
    cws.OpportunityOwnerRole,
    cws.OpportunityConverted,
    cws.OpportunityWonLostReason,
    cws.OpportunityOppStageBeforeLost,
    cws.OpportunityIsClosed,
    cws.OpportunityIsWon,
    cws.OwnerEmail,
    cws.OwnerFirstName,
    cws.OwnerLastName,
    cws.SubscriptionStartDate,
    cws.SubscriptionCapacity,
    cws.SubscriptionExpired,
    cws.SubscriptionStatus,
    cws.SubscriptionTerritory,
    cws.SubscriptionQuantity,
    cws.SubscriptionType,
    cws.ExistingAccount,
    cws.ActiveFullSubscriptions,
    cws.BDM_UserId,
    cws.BDM_UserName,
    cws.BDM_UserEmail,
    cws.BDM_Title
FROM [APAC_B2B_RE_Full&Ext_LAPSED_subscribers] cws

WHERE     
    cws.SubscriptionProduct LIKE '%Reading Eggs%' AND
    cws.ContactTerritory = 'APAC' AND
    cws.SubscriptionTerritory = 'APAC' AND
    cws.AccountBillingCountry  IN ('Australia','New Zealand') AND
    cws.SubscriptionEndDate    <= DATEADD(month, -1, GETDATE()) AND
    cws.SubscriptionEndDate    >  DATEADD(month, -18, GETDATE()) AND
    NOT EXISTS (Select c.Email from Contacts_With_Open_Opportunities c Where  cws.ContactEmail=c.Email )
