select 
LeadID, 
[Auto Trial],
FirstName,
LastName,
Date_Time,
[Job Title],
Description,
Email, 
Country,
State,
[Creation Date to today _Days_],
[Lead Status],
[Lead Stage],
[Product Code],
[Marketing Interest],
UserID,
[Full Name],
[First Name],
[Last Name],
Email_Seller, 
[Unread By Owner],
cid,
Title,
Phone,
[School Name],
[Last Modified Date],
[Last Modified By: Full Name],
datename(weekday, Date_Time) as Date
FROM [0006_AT_Lead-SellerProfiles_BData]
WHERE Country = 'United Kingdom'
OR Country LIKE '%Ireland%'