SELECT
     NEWID() as SubmissionId,
     (GETDATE() AT TIME ZONE 'Central Standard Time') AT TIME ZONE 'AUS Eastern Standard Time' as SubmittedDate,
     'False' as IsProcessed,
     FirstName, 
     LastName, 
     Email, 
     Phone, 
     MailingCity, 
     MailingCountry, 
     MailingCountryCode, 
     MailingPostalCode, 
     MailingState, 
     MailingStateCode, 
     MailingStreet, 
     Title, 
     Job_Function__c, 
     Contact_Source__c, 
     CurrencyIsoCode, 
     Campaign_Name__c, 
     Campaign_Code__c, 
     LeadSource, 
     Status, 
     Company, 
     FileName
FROM [001_Contact_Data_Import_to_CRM_STAGING]